language: en-US # must match a language from lang/*.json
veteran-time: 604800 # measured in seconds
stop-editing-on-shutdown: false
stop-editing-on-leave: true
auto-save:
  enabled: true
  interval: 300 # measured in seconds
exempt-claim-owner-from-permission-rules: true
enforce-adjacent-claim-chunks: true
allow-diagonal-claim-chunks: true
enter-chunk-editor-on-create: true
claim-min-distance: 0 # minimum distance (in chunks) between claimed chunks owned by different players
use-economy: false
limits:
  default:
     max-chunks: 20
     max-claims: 5
     max-claims-in-world: -1
     claim-price: 20
     unclaim-reward: 0
     free-chunks: 4
  sample-1:
    max-chunks: 50
    max-claims: 10
  sample-2:
    max-chunks: 25
    max-claims: 8
    give-after: 604800 # measured in seconds
dynmap-integration:
  enabled: true
  use-old-outline-style: false
  debug: false
worldguard-integration:
  enabled: true
  debug: false
disable-paper-warning: false
worlds:
  grace-time: 604800 # if a claim exists in a blacklisted world, the owner has this much time before it is removed (seconds)
  use-whitelist: false
  use-blacklist: false
  case-sensitive: true
  whitelist:
    - world
    - world_nether
    - world_the_end
  blacklist:
    - minigames
    - pvp
    - etc