language: en-US # must match a language from lang/*.json
veteran-time: 604800 # measured in seconds
stop-editing-on-shutdown: false
stop-editing-on-leave: true
exempt-claim-owner-from-permission-rules: true
enforce-adjacent-claim-chunks: true
allow-diagonal-claim-chunks: true
enter-chunk-editor-on-create: true
use-economy: false
limits:
  default:
     max-chunks: 20
     max-claims: 5
     max-claims-in-world: -1
     claim-price: 20
     unclaim-reward: 0
     free-chunks: 4
  sample-1:
    max-chunks: 50
    max-claims: 10
  sample-2:
    max-chunks: 25
    max-claims: 8
    give-after: 604800 # measured in seconds
dynmap-integration:
  enabled: true
  use-old-outline-style: false
