[versions]
annotations = "26.0.1"
jtoml       = "0.5.0"
bstats      = "3.1.0"
adventure   = "4.20.0"
mc-server   = "1.18.2-R0.1-SNAPSHOT"
reflections = "0.10.2" # is this even used?
gson        = "2.13.1"
caffeine    = "3.2.0"
sqlite      = "3.47.1.0"
vault       = "1.7"
essentials  = "2.20.1"
worldguard  = "7.0.9"
bluemap     = "2.7.3"
dynmap      = "3.6"
papi        = "2.11.6"

[libraries]
spigot-api                = { group = "org.spigotmc",                  name = "spigot-api",                      version.ref = "mc-server"   }
paper-api                 = { group = "io.papermc.paper",              name = "paper-api",                       version.ref = "mc-server"   }
reflections               = { group = "org.reflections",               name = "reflections",                     version.ref = "reflections" }
gson                      = { group = "com.google.code.gson",          name = "gson",                            version.ref = "gson"        }
caffeine                  = { group = "com.github.ben-manes.caffeine", name = "caffeine",                        version.ref = "caffeine"    }
adventure-api             = { group = "net.kyori",                     name = "adventure-api",                   version.ref = "adventure"   }
adventure-plain           = { group = "net.kyori",                     name = "adventure-text-serializer-plain", version.ref = "adventure"   }
adventure-minimessage     = { group = "net.kyori",                     name = "adventure-text-minimessage",      version.ref = "adventure"   }
adventure-platform-bukkit = { group = "net.kyori",                     name = "adventure-platform-bukkit",       version     = "4.4.0"       }
jtoml-core                = { group = "io.github.wasabithumb",         name = "jtoml",                           version.ref = "jtoml"       }
bstats-base               = { group = "org.bstats",                    name = "bstats-base",                     version.ref = "bstats"      }
bstats-bukkit             = { group = "org.bstats",                    name = "bstats-bukkit",                   version.ref = "bstats"      }
bstats-sponge             = { group = "org.bstats",                    name = "bstats-sponge",                   version.ref = "bstats"      }
annotations               = { group = "org.jetbrains",                 name = "annotations",                     version.ref = "annotations" }
sqlite                    = { group = "org.xerial",                    name = "sqlite-jdbc",                     version.ref = "sqlite"      }
vault-api                 = { group = "com.github.MilkBowl",           name = "VaultAPI",                        version.ref = "vault"       }
essentials                = { group = "net.essentialsx",               name = "EssentialsX",                     version.ref = "essentials"  }
worldguard-bukkit         = { group = "com.sk89q.worldguard",          name = "worldguard-bukkit",               version.ref = "worldguard"  }
bluemap-api               = { group = "de.bluecolored",                name = "bluemap-api",                     version.ref = "bluemap"     }
dynmap-core               = { group = "us.dynmap",                     name = "DynmapCoreAPI",                   version.ref = "dynmap"      }
dynmap-api                = { group = "us.dynmap",                     name = "dynmap-api",                      version.ref = "dynmap"      }
papi                      = { group = "me.clip",                       name = "placeholderapi",                  version.ref = "papi"        }
