# ╭─────────────────────────────────────╮ #
# │         _____ _       _             │ #
# │        / ____| |     (_)            │ #
# │  __  _| |    | | __ _ _ _ __ ___    │ #
# │  \ \/ / |    | |/ _` | | '_ ` _ \   │ #
# │   >  <| |____| | (_| | | | | | | |  │ #
# │  /_/\_\\_____|_|\__,_|_|_| |_| |_|  │ #
# │                                     │ #
# ╰─────────────────────────────────────╯ #

# GitHub Page: https://github.com/WasabiThumb/xclaim
# Hangar Page: https://hangar.papermc.io/WasabiThumbs/XClaim
# Spigot Page: https://www.spigotmc.org/resources/1-8-1-21-xclaim-better-chunk-claiming-for-smps.102843/
# This config file is in TOML format. Read the spec here: https://toml.io/en/v1.0.0

# The language pack to use. Must match a language in "lang/".
# English (en-US)
# German (de) by eingruenesbeb & derjungeinhd
# Chinese (zh) by SnowCutieOwO
# Turkish (tr) by Krayir5
language = "en-US"

# The time (in seconds) until a player is considered a Veteran.
veteran-time = 604800


[auto-save]
# Enables auto-saves.
enabled = true

# The time (in seconds) between each auto-save.
interval = 300

# Makes auto-saves complete silently.
silent = false


[editor]
# Opens the editor when a new claim is created.
start-on-create = true

# Kicks players out of the editor when the server shuts down.
stop-on-shutdown = false

# Kicks players out of the editor when the player leaves.
stop-on-leave = true


[gui]
# The height of the GUI. Must be between 3 and 6.
height = 4

# The default alignment of items when filling a row. Must be one of LEFT, CENTER, EVEN, RIGHT.
basis = "LEFT"

# The default dialog method. Must be one of ACTION_BAR, BOSS_BAR, CHAT.
dialog = "ACTION_BAR"


[rules]
# Enforces how chunks within the same claim can be placed in relation to eachother.
# 0 : No rule.
# 1 : Claims must be adjacent
# 2 : Claims must be adjacent or diagonal
placement = 2

# The minimum distance (in chunks) between claimed chunks owned by different players.
min-distance = 0

# Exempts claim owners from rules set inside their own claims. Probably shouldn't touch this.
exempt-owner = true

# Maximum chunks (in total) that a player can claim. Set to -1 for no limit.
max-chunks = 20
# Example using permissions (xclaim.group.test):
# max-chunks = { default = 20, test = 40 }

# Maximum claims (in total) that a player can have. Set to -1 for no limit.
max-claims = 5
# Example using permissions (xclaim.group.test):
# max-claims = { default = 5, test = 10 }

# Maximum claims (per world) that a player can have. Set to -1 for no limit.
max-claims-in-world = -1
# Example using permissions (xclaim.group.test):
# max-claims-in-world = { default = 2, test = -1 }


[worlds]
# If a claim exists in a blacklisted world, the owner has this much time before it is removed (seconds)
grace-time = 604800

# If the whitelist (below) should be used.
use-whitelist = false
whitelist = [ "world", "world_nether", "world_the_end" ]

# If the blacklist (below) should be used.
use-blacklist = false
blacklist = [ "minigames", "pvp", "etc" ]

# Controls whether the whitelist & blacklist is case-sensitive.
case-sensitive = true


# Controls claim permissions
# default: The default permitted group for new claims
# wild: The permitted group for all unclaimed chunks
# configurable: Whether the group may be changed by non-privileged players
[permissions]
build           = { default = "TRUSTED",  wild = "ALL", configurable = true } # Place/modify existing blocks
break           = { default = "TRUSTED",  wild = "ALL", configurable = true } # Break blocks
enter           = { default = "ALL",      wild = "ALL", configurable = true } # Move into the claim
use-storage     = { default = "TRUSTED",  wild = "ALL", configurable = true } # Use chests, barrels, shulker boxes
use-redstone    = { default = "TRUSTED",  wild = "ALL", configurable = true } # Activate powerable blocks
use-fixtures    = { default = "TRUSTED",  wild = "ALL", configurable = true } # Rotate item frames, dress armor stands
use-doors       = { default = "ALL",      wild = "ALL", configurable = true } # Use doors, gates, trapdoors
use-other       = { default = "ALL",      wild = "ALL", configurable = true } # Use crafting/enchanting tables, etc.
place-ents      = { default = "VETERANS", wild = "ALL", configurable = true } # Place armor stands, spawn eggs, etc.
place-vehicles  = { default = "VETERANS", wild = "ALL", configurable = true } # Place boats, minecarts, etc.
ignite          = { default = "TRUSTED",  wild = "ALL", configurable = true } # Create fire
explode         = { default = "TRUSTED",  wild = "ALL", configurable = true } # Cause explosions
damage-friendly = { default = "VETERANS", wild = "ALL", configurable = true } # Damage cows, sheep, squid, etc.
damage-hostile  = { default = "VETERANS", wild = "ALL", configurable = true } # Damage zombies, skeletons, etc.
damage-vehicles = { default = "VETERANS", wild = "ALL", configurable = true } # Damage boats, minecarts, etc.
damage-other    = { default = "ALL",      wild = "ALL", configurable = true } # Damage all other entities
drop-items      = { default = "ALL",      wild = "ALL", configurable = true } # Drop items
manage          = { default = "NONE",                   configurable = true } # Modify the claim settings
delete          = { default = "NONE",                   configurable = true } # Delete the claim


# Controls claim flags
# default: The default value for new claims
# configurable: Whether the value may be changed by non-privileged players
[flags]
no-pvp     = { default = false, configurable = true } # Disable all PvP
fireproof  = { default = false, configurable = true } # Disable all fire
waterproof = { default = false, configurable = true } # Disable all fluid penetration


[integrations.economy]
# Enables economy. If false, all other options in this section do not apply.
enabled = false

# The price to claim a chunk.
claim-price = 20
# Example using permissions (xclaim.group.test):
# claim-price = { default = 20, test = 10 }

# The amount of currency rewarded when unclaiming a chunk.
unclaim-reward = 0
# Example using permissions (xclaim.group.test):
# unclaim-reward = { default = 0, test = 5 }

# The number of chunks that can be claimed before claim-price takes effect.
free-chunks = 4
# Example using permissions (xclaim.group.test):
# free-chunks = { default = 4, test = 8 }


[integrations.map]
# Enables map integration (Bluemap, Dynmap). If false, all other options in this section do not apply.
enabled = true

# Uses convex hull outlines. Try only if outlines seem bugged.
old-outline-style = false

# Reserved.
debug = false


[integrations.protection]
# Enables protection integration (Worldguard). If false, all other options in this section do not apply.
enabled = true

# Reserved.
debug = false


